# Generated by Django 2.2.24 on 2021-12-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wzs_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
