# Generated by Django 2.0.8 on 2019-01-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pirate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('money', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
