# Generated by Django 2.0.8 on 2019-01-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20190118_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
