# Generated by Django 2.0.8 on 2019-01-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190115_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='addr',
            field=models.CharField(default='地址', max_length=128),
            preserve_default=False,
        ),
    ]
