# Generated by Django 2.0.8 on 2019-01-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_publisher_addr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, unique=True)),
                ('book', models.ManyToManyField(to='app01.Book')),
            ],
        ),
    ]
