# Generated by Django 2.0.8 on 2019-01-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(auto_now_add=True, default='2019-01-16'),
            preserve_default=False,
        ),
    ]
